# Generated by Django 4.2.6 on 2023-11-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='gallery')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
