# Generated by Django 4.2.6 on 2023-11-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_datedcompleted_task_datecompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=20)),
                ('nomorg', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('mensaje', models.TextField(max_length=1000)),
            ],
        ),
    ]
