# Generated by Django 4.2.6 on 2023-11-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default='Asunto', max_length=200),
        ),
    ]
