# Generated by Django 4.2.6 on 2023-11-07 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_contacto_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='created',
            field=models.DateTimeField(default=datetime.date(2023, 11, 7)),
        ),
    ]
