# Generated by Django 4.2.6 on 2023-11-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_contacto_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
