# Generated by Django 4.2.6 on 2023-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_contacto_telefono_alter_contacto_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tip_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
